In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

%matplotlib inline
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt



# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

dir = []
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [4]:
df = pd.read_csv

In [5]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.head()

In [6]:
def check_dtypes_1(df):
    '''
    Parameters :
    ------------
    df : Dataframe name 

    Step :
    ------
    > 1. Do iteration for each feature to define which one categorical and nummerical feature. 
    > 2. Columns in dataframe will be seperated based on the dtypes
    > 3. All of the column will be entered to the list that have been created

    result :
    --------
    The result will be formed as dataframe
    '''
    # Make a list for both of the data type 
    categorical_list = []
    numerical_list = []
    
    #Looping 
    for col in df.columns.tolist():
        if df[col].dtype=='object':
            categorical_list.append(col)
        else:
            numerical_list.append(col)
    
    #make dataframe that have two feature, that is categorical and numerical feature
    categorical = pd.Series(categorical_list, name='Categorical Feature')
    numerical = pd.Series(numerical_list, name='Numerical Feature')
    df_dtypes = pd.concat([categorical,numerical], axis=1)
    
    return df_dtypes

In [7]:
#1. Input dataframe
dataframe = df
#2. Seperated 
check_dtypes_1(dataframe)

In [8]:
def list_dtypes(df):
    categorical_list = []
    numerical_list = []
    for col in df.columns.tolist():
        if df[col].dtype=='object':
            categorical_list.append(col)
        else:
            numerical_list.append(col)
    print('Number of categorical features:', str(len(categorical_list)))
    print('Number of numerical features:', str(len(numerical_list)))

    return categorical_list, numerical_list

In [9]:
categorical_list, numerical_list = list_dtypes(df)

In [10]:
# module Check missing value 
def missing_value(df):
    '''
    Documentation :
    --------------
    * df : Dataframe Name
    '''
    #count the number of missing value 
    total = df.isnull().sum().sort_values(ascending = False)
    percent = round(df.isnull().sum()/len(df)*100,2).sort_values(ascending = False)
    missing  = pd.concat([total, percent], axis=1, keys=['Total_Missing', 'Percent(%)'])
    
    return missing.head(20)

In [11]:
#1. input dataframe
dataframe = df

#2. input dataframe to the module 
missing_value(dataframe)

In [12]:
def fill_missing(df, feature_list = None , vartype = None ):
    '''
    Documentation :
    ---------------
    df              : object, dataframe
    feature_list    : feature list is the set of numerical or categorical features 
                      that have been seperated before
    vartype         : variable type : continuos or categorical, default (numerical)
                        (0) numerical   : variable type continuos/numerical
                        (1) categorical : variable type categorical
    Note :
    ------
    > if numerical variable will be filled by median 
    > if categorical variabe will filled by modus
    > if have been made variebles based on the dtypes list before, 
      insert it into feature list in the function.     

    Example :
    ---------
    # 1. Define feature that will be filled in 
      num_feature = numeric_list
 # 2. Input Dataframe
      dataframe = df
      
    # 3. Vartype
      var_type = 0
      
    # 4. Filling Value
      Fill_missing(dataframe, num_feature, var_type)
    '''
    #default vartype 
    if vartype == None :
        vartype = 'numerical'

    # filling numerical data with median 
    if vartype == 'numerical' :
        for col in feature_list:
            df[col] = df[col].fillna(df[col].median())
    
    # filling categorical data with modus  
    if vartype == 'categorical' :
        for col in feature_list:
            df[col] = df[col].fillna(df[col].mode().iloc[0])

In [13]:
# 1. define feature that will be filled in 
num_feature = numerical_list

# 3. Vartype
var_type = 'numerical'

# 4. Filling Value
fill_missing(df, num_feature, var_type)

In [14]:
# 1. define feature that will be filled in 
cat_feature = categorical_list

# 2. Vartype
var_type = 'categorical'

# 3. Filling Value
fill_missing(df, cat_feature, var_type)

In [15]:
# Df Numeric 
df_num_list = df[numerical_list]
df_num_list.drop('Job',axis=1,inplace=True)
df_num_list.head()

In [16]:
# Df categoric 
df_categ = df[categorical_list]
df_categ['Job'] = df['Job']
df_categ.head()

In [17]:
for x in range(len(df)):
    if df['Job'][x]==0:
        df['Job'][x]='unskilled and non-resident'
    if df['Job'][x]==1:
        df['Job'][x]='unskilled and resident'
    if df['Job'][x]==2:
        df['Job'][x]='skilled'
    if df['Job'][x]==3:
        df['Job'][x]='highly skilled'

In [18]:
df2=df.copy()

In [19]:
df2.head()

In [20]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

%matplotlib inline
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt



# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

dir = []
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.
/kaggle/input/german-credit/german_credit_data.csv
Load Data
df = pd.read_csv('/kaggle/input/german-credit/german_credit_data.csv')
df.drop('Unnamed: 0',axis=1,inplace=True)
df.head()
Age	Sex	Job	Housing	Saving accounts	Checking account	Credit amount	Duration	Purpose
0	67	male	2	own	NaN	little	1169	6	radio/TV
1	22	female	2	own	little	moderate	5951	48	radio/TV
2	49	male	1	own	little	NaN	2096	12	education
3	45	male	2	free	little	little	7882	42	furniture/equipment
4	53	male	2	free	little	little	4870	24	car
Check Data Types
def check_dtypes_1(df):
    '''
    Parameters :
    ------------
    df : Dataframe name 

    Step :
    ------
    > 1. Do iteration for each feature to define which one categorical and nummerical feature. 
    > 2. Columns in dataframe will be seperated based on the dtypes
    > 3. All of the column will be entered to the list that have been created

    result :
    --------
    The result will be formed as dataframe
    '''
    # Make a list for both of the data type 
    categorical_list = []
    numerical_list = []
    
    #Looping 
    for col in df.columns.tolist():
        if df[col].dtype=='object':
            categorical_list.append(col)
        else:
            numerical_list.append(col)
    
    #make dataframe that have two feature, that is categorical and numerical feature
    categorical = pd.Series(categorical_list, name='Categorical Feature')
    numerical = pd.Series(numerical_list, name='Numerical Feature')
    df_dtypes = pd.concat([categorical,numerical], axis=1)
    
    return df_dtypes
#1. Input dataframe
dataframe = df
#2. Seperated 
check_dtypes_1(dataframe)
Categorical Feature	Numerical Feature
0	Sex	Age
1	Housing	Job
2	Saving accounts	Credit amount
3	Checking account	Duration
4	Purpose	NaN
List Types
def list_dtypes(df):
    categorical_list = []
    numerical_list = []
    for col in df.columns.tolist():
        if df[col].dtype=='object':
            categorical_list.append(col)
        else:
            numerical_list.append(col)
    print('Number of categorical features:', str(len(categorical_list)))
    print('Number of numerical features:', str(len(numerical_list)))

    return categorical_list, numerical_list
categorical_list, numerical_list = list_dtypes(df)
Number of categorical features: 5
Number of numerical features: 4
Check Missing Value
Function to make missing value gone. Using median for numerical and mode for categorical.

# module Check missing value 
def missing_value(df):
    '''
    Documentation :
    --------------
    * df : Dataframe Name
    '''
    #count the number of missing value 
    total = df.isnull().sum().sort_values(ascending = False)
    percent = round(df.isnull().sum()/len(df)*100,2).sort_values(ascending = False)
    missing  = pd.concat([total, percent], axis=1, keys=['Total_Missing', 'Percent(%)'])
    
    return missing.head(20)
#1. input dataframe
dataframe = df

#2. input dataframe to the module 
missing_value(dataframe)
Total_Missing	Percent(%)
Checking account	394	39.4
Saving accounts	183	18.3
Purpose	0	0.0
Duration	0	0.0
Credit amount	0	0.0
Housing	0	0.0
Job	0	0.0
Sex	0	0.0
Age	0	0.0
Fill Missing
def fill_missing(df, feature_list = None , vartype = None ):
    '''
    Documentation :
    ---------------
    df              : object, dataframe
    feature_list    : feature list is the set of numerical or categorical features 
                      that have been seperated before
    vartype         : variable type : continuos or categorical, default (numerical)
                        (0) numerical   : variable type continuos/numerical
                        (1) categorical : variable type categorical
    Note :
    ------
    > if numerical variable will be filled by median 
    > if categorical variabe will filled by modus
    > if have been made variebles based on the dtypes list before, 
      insert it into feature list in the function.     

    Example :
    ---------
    # 1. Define feature that will be filled in 
      num_feature = numeric_list
      
    # 2. Input Dataframe
      dataframe = df
      
    # 3. Vartype
      var_type = 0
      
    # 4. Filling Value
      Fill_missing(dataframe, num_feature, var_type)
    '''
    #default vartype 
    if vartype == None :
        vartype = 'numerical'

    # filling numerical data with median 
    if vartype == 'numerical' :
        for col in feature_list:
            df[col] = df[col].fillna(df[col].median())
    
    # filling categorical data with modus  
    if vartype == 'categorical' :
        for col in feature_list:
            df[col] = df[col].fillna(df[col].mode().iloc[0])
# 1. define feature that will be filled in 
num_feature = numerical_list

# 3. Vartype
var_type = 'numerical'

# 4. Filling Value
fill_missing(df, num_feature, var_type)
# 1. define feature that will be filled in 
cat_feature = categorical_list

# 2. Vartype
var_type = 'categorical'

# 3. Filling Value
fill_missing(df, cat_feature, var_type)
# Df Numeric 
df_num_list = df[numerical_list]
df_num_list.drop('Job',axis=1,inplace=True)
df_num_list.head()
/opt/conda/lib/python3.6/site-packages/pandas/core/frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
Age	Credit amount	Duration
0	67	1169	6
1	22	5951	48
2	49	2096	12
3	45	7882	42
4	53	4870	24
# Df categoric 
df_categ = df[categorical_list]
df_categ['Job'] = df['Job']
df_categ.head()
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
Sex	Housing	Saving accounts	Checking account	Purpose	Job
0	male	own	little	little	radio/TV	2
1	female	own	little	moderate	radio/TV	2
2	male	own	little	little	education	1
3	male	free	little	little	furniture/equipment	2
4	male	free	little	little	car	2
Label Encoder
Change numerical to categorical with rules: Job (numeric: 0 - unskilled and non-resident, 1 - unskilled and resident, 2 - skilled, 3 - highly skilled)

for x in range(len(df)):
    if df['Job'][x]==0:
        df['Job'][x]='unskilled and non-resident'
    if df['Job'][x]==1:
        df['Job'][x]='unskilled and resident'
    if df['Job'][x]==2:
        df['Job'][x]='skilled'
    if df['Job'][x]==3:
        df['Job'][x]='highly skilled'
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/opt/conda/lib/python3.6/site-packages/pandas/core/indexing.py:202: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
df2=df.copy()
df2.head()
Age	Sex	Job	Housing	Saving accounts	Checking account	Credit amount	Duration	Purpose
0	67	male	skilled	own	little	little	1169	6	radio/TV
1	22	female	skilled	own	little	moderate	5951	48	radio/TV
2	49	male	unskilled and resident	own	little	little	2096	12	education
3	45	male	skilled	free	little	little	7882	42	furniture/equipment
4	53	male	skilled	free	little	little	4870	24	car
df2=pd.get_dummies(df2,prefix

In [21]:
def distributions(df):
    plt.figure(figsize=(10,5))
    fig, (ax1, ax2, ax3) = plt.subplots(3,1, figsize=(8,8))
    sns.distplot(df["Age"], ax=ax1)
    sns.distplot(df["Credit amount"], ax=ax2)
    sns.distplot(df["Duration"], ax=ax3)
    plt.tight_layout()

In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [23]:
df3 = df2_log.copy()
df3_num = df3

In [24]:
df3_num

In [25]:
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
wcss = []
K = range(1,10)
for k in K:
    km = KMeans(n_clusters=k)
    km = km.fit(df3_num)
    wcss.append(km.inertia_)
plt.plot(K, wcss, 'bx-')
plt.xlabel('Number of centroids')
plt.ylabel('')
plt.title('Elbow Method For Optimal k')
plt.show()

In [26]:
df_kmeans = df3_num.copy()
kmeans = KMeans(n_clusters=3)
kmeans.fit(df_kmeans)

In [27]:
from sklearn.metrics import silhouette_score
silhouette_score(df_kmeans, kmeans.labels_)

In [28]:
from sklearn.metrics import silhouette_score
silhouette_score(df_kmeans, kmeans.labels_)

In [29]:
from mpl_toolkits import mplot3d

In [30]:
import seaborn as sns; sns.set()

plt.figure(figsize=(15,10))
ax = plt.axes(projection='3d')

xdata = df['Age']
ydata = df['Credit amount']
zdata = df['Duration']

ax.set_xlabel('Age')
ax.set_ylabel('Credit amount')
ax.set_zlabel('Duration')

ax.scatter3D(xdata, ydata, zdata, c=df_kmeans['kluster'], cmap='viridis');

In [31]:
plt.figure(figsize=(15,5))
import scipy.cluster.hierarchy as sch

dendogram = sch.dendrogram(sch.linkage(df3_num, method='ward'))

In [32]:
from sklearn.cluster import DBSCAN

In [33]:
df_dbscan = df3_num.copy()

In [34]:
dbscan = DBSCAN(eps=0.09, min_samples=5)
dbscan.fit(df_dbscan)

In [35]:
DBSCAN(algorithm='auto', eps=0.09, leaf_size=30, metric='euclidean',
       metric_params=None, min_samples=5, n_jobs=None, p=None)
import seaborn as sns; sns.set()

plt.figure(figsize=(15,10))
ax = plt.axes(projection='3d')

xdata = df['Age']
ydata = df['Credit amount']
zdata = df['Duration']

ax.set_xlabel('Age')
ax.set_ylabel('Credit amount')
ax.set_zlabel('Duration')

ax.scatter3D(xdata, ydata, zdata, c=dbscan.labels_, cmap='viridis');

In [36]:
df['k_means_label'] = kmeans.labels_

In [37]:
for x in range(len(df)):
    if df['k_means_label'][x]==0:
        df['k_means_label'][x]='medium'
    if df['k_means_label'][x]==1:
        df['k_means_label'][x]='good'
    if df['k_means_label'][x]==2:
        df['k_means_label'][x]='bad'

In [38]:
fig = plt.figure(figsize=(12,6))
plt.title('Count Plot',fontsize = 20)
ax=sns.countplot(data=df, x='Sex',hue="k_means_label")
ax.set_xlabel('Sex', fontsize = 15)
ax.tick_params(labelsize=12)

In [39]:
fig = plt.figure(figsize=(12,6))
plt.title('Count Plot',fontsize = 20)
ax=sns.countplot(data=df, x='Job',hue="k_means_label")
ax.set_xlabel('Job', fontsize = 15)
ax.tick_params(labelsize=12)

In [40]:
fig = plt.figure(figsize=(12,6))
plt.title('Count Plot',fontsize = 20)
ax=sns.countplot(data=df, x='Purpose',hue="k_means_label")
ax.set_xlabel('Purpose', fontsize = 15)
ax.tick_params(labelsize=12)
plt.xticks(rotation=30)